#!/bin/bash
# -*- sh -*-

CONF=/etc/nginx/sites-enabled/discourse.conf

sed -i s/\$HOSTIP/$HOSTIP/ $CONF
sed -i s/\$SITE_PORT/$DISCOURSE_PORT/ $CONF
sed -i s/\$SITE_NAME/$DISCOURSE_HOST/ $CONF

CONF=/etc/nginx/sites-enabled/our.conf

sed -i s/\$HOSTIP/$HOSTIP/ $CONF
sed -i s/\$SITE_PORT/$OUR_PORT/ $CONF
sed -i s/\$SITE_NAME/$OUR_HOST/ $CONF

