#!/bin/bash
# -*- sh -*-

CONF=/etc/nginx/sites-enabled/discourse.conf

sed -i s/\$SITE_HOST/$SITE_HOST/ $CONF
sed -i s/\$SITE_PORT/$SITE_PORT/ $CONF
sed -i s/\$SITE_NAME/$SITE_NAME/ $CONF

CONF=/etc/nginx/sites-enabled/our.conf

sed -i s/\$SITE_HOST/$SITE_HOST/ $CONF
sed -i s/\$SITE_PORT/$SITE_PORT/ $CONF
sed -i s/\$SITE_NAME/$SITE_NAME/ $CONF

exec nginx



